### ISSUE TITLE
Pass values to a HTML page created using IWebBrowser2 in c++  

### ISSUE THREAD

**Issue by ShivaniPahuja02** [DNS/WinAPI-Embed-Browser#1]
We are using https://www.codeproject.com/Articles/3365/Embed-an-HTML-control-in-your-own-window-using-pla  to Embed an HTML control in your own window.but we want communication between Window and page as well.
Is there is any exposed function to call HTML page  javascript function from Window  and get its return value.

**Comment by DNS** [comment]
Sorry, I don't know about that.
